'package: @woocommerce/api':
- packages/js/@woocommerce/api/**/*

'package: @woocommerce/e2e-utils':
- packages/js/@woocommerce/e2e-utils/**/*

'package: @woocommerce/e2e-environment':
- packages/js/@woocommerce/e2e-environment/**/*

'package: @woocommerce/api-core-tests':
- packages/js/@woocommerce/api-core-tests/**/*

'package: @woocommerce/e2e-core-tests':
- packages/js/@woocommerce/e2e-core-tests/**/*

'package: @woocommerce/admin-e2e-tests':
- packages/js/@woocommerce/admin-e2e-tests/**/*

'package: @woocommerce/components':
- packages/js/@woocommerce/components/**/*

'package: @woocommerce/csv-export':
- packages/js/@woocommerce/csv-export/**/*

'package: @woocommerce/currency':
- packages/js/@woocommerce/currency/**/*

'package: @woocommerce/customer-effort-score':
- packages/js/@woocommerce/customer-effort-score/**/*

'package: @woocommerce/data':
- packages/js/@woocommerce/data/**/*

'package: @woocommerce/date':
- packages/js/@woocommerce/date/**/*

'package: dependency-extraction-webpack-plugin':
- packages/js/@woocommerce/dependency-extraction-webpack-plugin/**/*

'package: @woocommerce/eslint-plugin':
- packages/js/@woocommerce/eslint-plugin/**/*

'package: @woocommerce/experimental':
- packages/js/@woocommerce/experimental/**/*

'package: @woocommerce/explat':
- packages/js/@woocommerce/explat/**/*

'package: @woocommerce/navigation':
- packages/js/@woocommerce/navigation/**/*

'package: @woocommerce/number':
- packages/js/@woocommerce/number/**/*

'package: @woocommerce/onboarding':
- packages/js/@woocommerce/onboarding/**/*

'package: @woocommerce/tracks':
- packages/js/@woocommerce/tracks/**/*

'plugin: woocommerce':
- plugins/woocommerce/**/*

'focus: react admin':
- plugins/woocommerce/src/Admin/**/*
- plugins/woocommerce/src/Internal/Admin/**/*
- plugins/woocommerce-admin/**/*
