name: Install and Build (Composite)
description: Installs and builds WooCommerce.
inputs:
  working_directory:
    required: false
    description: The directory to target.
    default: ./

runs:
  using: "composite"
  steps:
    - name: Install PNPM
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: npm install -g pnpm@^6.24.2

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: pnpm install

    - name: Install Composer dependencies
      # Temporarily disable this step for testing
      if: ${{ false }}    
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: pnpm nx composer-install-no-dev woocommerce

    - name: Run build
      # Temporarily disable this step for testing
      if: ${{ false }}       
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: pnpm nx build woocommerce
